### ISSUE TITLE
Sanity check our approaches to insertion, deletion frequencies & basecalling error

### ISSUE THREAD

**Issue by lkwhite** [rnabioco/detectrms-rs#2]
I've been playing with this some for the tRNA data, and it's easy to get positions where bcerror > 1 if you calculate based on mapped nt depth. Here's what I'm leaning towards:

- mismatch frequency = mismatched bases / bases mapped at position
- insertion frequency = insertion events / bases mapped at position
- deletion frequency = deletion events / reads spanning the position
- basecalling error frequency = (mismatched bases + insertion events + deletion events) / reads spanning the position
- mean qscore = mean(qscore for mapped bases at the position)

Let me know what you think. I've got a purely python implementation over [here](https://github.com/rnabioco/tRNA004/blob/main/src/get_bcerror_freqs.py) that I wrote in a way that's probably not as efficient, but maximally readable to me.

**Comment by MLKaufman** [comment]
I have made a separate branch to address this and made an attempt to update it, but haven't tested it yet.
https://github.com/rnabioco/detectrms-rs/tree/bases-mapped
